/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: 'Wo5dMEP_BbI',
    title:
      'Top 10 Legendary Goalkeepers In Football ● Lev Yashin ● René Higuita ● Oliver Kahn ● & More',
    description:
      'The Top 10 Legendary Goalkeepers in Football! The top 10 includes the goalkeepers Lev Yashin, René Higuita, Oliver Kahn, Manuel Neuer, Gianluigi Buffon, Iker Casillas, Petr Cech, Dino Zoff, Peter Schmeichel, and David Seaman! Enjoy all the amazing and impossible saves! These rankings are not in any particular order so comment down below how you would rank this top 10! If you enjoyed, then be sure to like, comment and subscribe to see more awesome content in the future! ',
    creator: 'ImJabzter',
    views: 6361236,
    createdAt: '2019-07-30',
    thumbnail: 'https://i.postimg.cc/4d1Hq0Vb/top-10-goalie.jpg',
    videoLink: 'https://www.youtube.com/watch?v=9moTCEthCs0',
  },
  {
    _id: 'F_Riqjdh2oM',
    title: 'Best 50 Goalkeeper Saves 2023',
    description: 'Best saves by Goalkeeper in 2023',
    creator: 'EFB HD',
    views: 288945,
    createdAt: '2023-01-04',
    thumbnail: 'https://i.postimg.cc/8cVwBxDR/best-save-2023.jpg',
    videoLink: 'https://www.youtube.com/watch?v=w21Ou6dJEvY',
    category: 'Best Save',
  },
  {
    _id: 'Sg7r8uEefs',
    title: '100 Greatest Goalkeeper Saves In Football History',
    description:
      '100 Greatest Goalkeeper Saves In Football History ft. Gianluigi Buffon, Peter Schmeichel, Gordon Banks, Rene Higuita, Lev Yashin, Iker Casillas, Oliver Kahn, David De Gea, Manuel Neuer etc. If you enjoyed the video, give it a thumbs up and subscribe for new videos!',
    creator: 'Notelicioux',
    views: 1319053,
    createdAt: '2022-08-22',
    thumbnail: 'https://i.postimg.cc/Vk1QLHCb/best-100-save.jpg',
    category: 'Best Save',
  },
  {
    _id: 'I9Xpsu854W',
    title: 'Iker Casillas Was an Absolute Monster',
    description:
      'Legendary saves from one of the best goalkeepers in history Iker Casillas',
    creator: 'mr bundesteam',
    views: 5022865,
    createdAt: '2022-10-04',
    thumbnail: 'https://i.postimg.cc/PrHTPxGx/iker-casillas.jpg',
    category: 'Best Save',
    videoLink: 'https://www.youtube.com/watch?v=oLgWGVqWSak',
  },

  {
    _id: 'A2veWd7IBW',
    title: 'Top 20 Free Kicks Ever in Football History',
    description:
      'Amazing freekick goals from Beckham, Cristiano Ronaldo, Lionel Messi, Ronaldinho and more.',
    creator: 'JavierNathaniel',
    videoLink: 'https://www.youtube.com/watch?v=zSg-00p2ES4',
    views: 13744930,
    createdAt: '2015-04-29',
    thumbnail: 'https://i.postimg.cc/Dy20VBkp/sddefault.jpg',
    category: 'Best FreeKick',
  },
  {
    _id: 'QYqwf5gL30',
    title: 'Legendary Free Kicks',
    description: 'Here are the most legendary free kicks ever scored in football.',
    creator: 'Score 90',
    videoLink: 'https://www.youtube.com/watch?v=ORG9O0Yvpf0',
    views: 9363082,
    createdAt: '2020-10-20',
    thumbnail: 'https://i.postimg.cc/XqYRLZmL/sddefault.jpg',
    category: 'Best Freekick',
  },
  {
    _id: 'ItOLj97qQY',
    title: 'Top 10 Incredible Free Kick Goals Of The Year',
    description:
      'Best 10 free kick goals of the year 2019! Dybala, Ronaldo, Messi, Rashford and more in video.',
    creator: 'TKHD',
    videoLink: 'https://www.youtube.com/watch?v=daW7J5kdjv8',
    views: 50246839,
    createdAt: '2019-12-28',
    thumbnail: 'https://i.postimg.cc/htBHZ3kh/sddefault.jpg',
    category: 'Best Freekick',
  },
  {
    _id: 'ieqYTbAXev',
    title: '100 Best Free Kicks In Football History',
    description:
      '100 Best Free Kicks In Football History ft. Juninho, Lionel Messi, Cristiano Ronaldo, Ronaldinho, Roberto Carlos, David Beckham, Andrea Pirlo, Sinisa Mihajlovic etc. If you enjoyed the video, give it a thumbs up and subscribe for new videos!',
    creator: 'Notelicioux',
    videoLink: 'https://www.youtube.com/watch?v=pwGgHS0D-rg',
    views: 3829839,
    createdAt: '2019-11-18',
    thumbnail: 'https://i.postimg.cc/RhGHrYP9/sddefault.jpg',
    category: 'Best Freekick',
  },

  {
    _id: 'GfVzuK7CiJ',
    title: 'Humiliating Skills That Ended Players Career in Football',
    description:
      ' 5,000 LIKE ON" Humiliating Skills That Ended Players Career in Football"',
    creator: 'JackieMt',
    videoLink: 'https://www.youtube.com/watch?v=ZkHtK33QdU0',
    views: 7944137,
    createdAt: '2020-03-24',
    thumbnail: 'https://i.postimg.cc/7ZjXQCG9/sddefault.jpg',
    category: 'Skills',
  },
  {
    _id: 'yXATey34cj',
    title: '15 BEST Skill Moves to Beat Defenders in REAL GAMES',
    description:
      '15 GREAT Skill Moves to Beat Defenders in Soccer or Football. Simple and Easy match skills to use in real games. Learn these moves with AllAttack!',
    creator: 'AllAttack',
    videoLink: 'https://www.youtube.com/watch?v=L8taGwfp2sU',
    views: 32450130,
    createdAt: '2019-06-29',
    thumbnail: 'https://i.postimg.cc/HLfK5Z9p/sddefault.jpg',
    category: 'Skills',
  },
  {
    _id: 'LErPh1BPt8',
    title: 'Top 50+ Unique & Original Football Skills',
    description:
      "What's the player that you have in your mind when we talk about unique and original skills? Ronaldinho? Neymar? Brazilians are definitely dominant players in this segment of football.  Skills that will blow your mind, Thabo Qalinge is absolutely sensational, how will you named that kind of skill? He's rolling around the ball, dancing... We named it 360° Stepovers. Check out all others in the video!",
    creator: 'Home of Football',
    videoLink: 'https://www.youtube.com/watch?v=OOvyseZM1gQ',
    category: 'Skills',
    views: 7064960,
    createdAt: '2019-08-24',
    thumbnail: 'https://i.postimg.cc/28Qz5vmb/sddefault.jpg',
  },
  {
    _id: 'eCj0CzZzwg',
    title: 'TOP 10 Cristiano Ronaldo Skills',
    description: 'The top 10 skills done by Cristiano Ronaldo',
    creator: 'AllAttack',
    videoLink: 'https://www.youtube.com/watch?v=qsNKYgx6KCg',
    views: 2286567,
    createdAt: '2021-06-30',
    thumbnail: 'https://i.postimg.cc/P5bN09N7/sddefault.jpg',
    category: 'Skills',
  },
  {
    _id: 'DHsmt6F9ag',
    title: '50 Skills you can use to Beat a PRO Footballer !?',
    description:
      'YES GUYS! WELCOME BACK! Check out these 50 (yes, FIFTY) skills you can use to try and get past a defender! Starting from Easy to Hard, watch until the end for the best ones! Hopefully you guys enjoy the video, if so please dont forget to SMASH THE LIKE BUTTON! Drop a comment below & dont forget to subscribe!',
    creator: 'LDN Movements',
    videoLink: 'https://www.youtube.com/watch?v=9BRxdzFk6IQ',
    views: 5165732,
    createdAt: '2020-07-19',
    thumbnail: 'https://i.postimg.cc/NMk3c8RB/sddefault.jpg',
    category: 'Skills',
  },
  {
    _id: '9lEuuima36',
    title: '10 Star skills in football',
    description:
      "In this video, we're going to share with you some of the 10 star skills starring Okocha, Messi, Cristiano Ronaldo...",
    creator: 'SportsHD',
    videoLink: 'https://www.youtube.com/watch?v=-JTaMShegnA',
    views: 93323,
    createdAt: '2023-01-20',
    thumbnail: 'https://i.postimg.cc/d3d4Fwbd/sddefault.jpg',
    category: 'Skills',
  },

  {
    _id: 'yj5Tv7BVrO',
    title: '20 CRAZIEST Goals In Football History',
    description: 'These are the 20 CRAZIEST Goals in Football History.. ',
    creator: 'KickFlix',
    videoLink: 'https://www.youtube.com/watch?v=y8H9AOf413M',
    views: 7020133,
    createdAt: '2022-01-29',
    thumbnail: 'https://i.postimg.cc/wjhc09JR/sddefault.jpg',
    category: 'Best Goals',
  },
  {
    _id: 'PbV99VrIsY',
    title: '0.0001% Chance Goals',
    description: 'TURN ON NOTIFICATIONS TO NEVER MISS AN UPLOAD!',
    creator: 'AshStudio7',
    videoLink: 'https://www.youtube.com/watch?v=Da6h6K4Lqto',
    views: 4405759,
    createdAt: '2022-08-09',
    thumbnail: 'https://i.postimg.cc/RCK1LctV/sddefault.jpg',
    category: 'Best Goals',
  },
  {
    _id: 'sMTDROBHpQ',
    title: 'Unforgettable Goals In Football History #1',
    description:
      'Hello, we have prepared unforgettable goals in the history of football in this video for you. It took us about a 2 week to prepare the video. I hope you like this video, which we prepared by using various internet sites. Like and keep comments for more. Have a good time.',
    creator: 'BTGL TV',
    videoLink: 'https://www.youtube.com/watch?v=GMmGt0upVrY',
    views: 23719140,
    createdAt: '2019-08-23',
    thumbnail: 'https://i.postimg.cc/D08tRx3D/sddefault.jpg',
    category: 'Best Goals',
  },
  {
    _id: 'WBFPZ4Fyao',
    title: 'Best Last Minute Goals Ever in Football',
    description:
      'Best Last Minute Goals Ever in Football, There are many goals in football every week. But some goals are memorable...Sometimes one goal can change many life.Specialy, if it come in last minutes…',
    creator: 'Terso Isler',
    videoLink: 'https://www.youtube.com/watch?v=Cw7AArqO-CE',
    views: 19818969,
    createdAt: '2019-07-15',
    thumbnail: 'https://i.postimg.cc/vHvN3RnB/sddefault.jpg',
    category: 'Best Goals',
  },
  {
    _id: 'YQ50cdrwx0',
    title: 'Best Rocket Goals in Football #1',
    description:
      'The best rocket-like goals. Cristiano Ronaldo, Ibrahimovic, Hulk, Agüero, Paulinho, Di Maria, Roberto Carlos and more in video!',
    creator: 'TKHD',
    videoLink: 'https://www.youtube.com/watch?v=b0M8Z37T36U',
    views: 9859867,
    createdAt: '2019-10-05',
    thumbnail: 'https://i.postimg.cc/DyDXV0LY/sddefault.jpg',
    category: 'Best Goals',
  },
];
